import * as mat from "@angular/material";

import * as prime from "primeng/primeng";

import * as app from "./";

export { AppComponent } from "./app.component";

export const Apps = [app.AppComponent];

export const MaterialModule = [
	mat.MatCheckboxModule,
	mat.MatCheckboxModule,
	mat.MatButtonModule,
	mat.MatInputModule,
	mat.MatAutocompleteModule,
	mat.MatDatepickerModule,
	mat.MatFormFieldModule,
	mat.MatRadioModule,
	mat.MatSelectModule,
	mat.MatSliderModule,
	mat.MatSlideToggleModule,
	mat.MatMenuModule,
	mat.MatSidenavModule,
	mat.MatToolbarModule,
	mat.MatListModule,
	mat.MatGridListModule,
	mat.MatCardModule,
	mat.MatStepperModule,
	mat.MatTabsModule,
	mat.MatExpansionModule,
	mat.MatButtonToggleModule,
	mat.MatNativeDateModule,
	mat.MatChipsModule,
	mat.MatIconModule,
	mat.MatProgressSpinnerModule,
	mat.MatProgressBarModule,
	mat.MatDialogModule,
	mat.MatTooltipModule,
	mat.MatSnackBarModule,
	mat.MatTableModule,
	mat.MatSortModule,
	mat.MatPaginatorModule,
	mat.MatRippleModule
];

export const PrimengModule = [
	prime.AccordionModule,
	prime.BlockUIModule,
	prime.BreadcrumbModule,
	prime.ButtonModule,
	prime.CalendarModule,
	prime.CaptchaModule,
	prime.CardModule,
	prime.CarouselModule,
	// prime.ChartModule,
	prime.CheckboxModule,
	prime.ChipsModule,
	prime.CodeHighlighterModule,
	prime.ContextMenuModule,
	prime.ConfirmDialogModule,
	prime.DataGridModule,
	prime.DataListModule,
	prime.DataScrollerModule,
	prime.DialogModule,
	prime.DragDropModule,
	// prime.EditorModule,
	prime.FieldsetModule,
	prime.FileUploadModule,
	prime.GMapModule,
	prime.GalleriaModule,
	prime.GrowlModule,
	prime.InputMaskModule,
	prime.InputSwitchModule,
	prime.InputTextModule,
	prime.InputTextareaModule,
	prime.KeyFilterModule,
	prime.LightboxModule,
	prime.ListboxModule,
	prime.MegaMenuModule,
	prime.MultiSelectModule,
	prime.MenuModule,
	prime.MenubarModule,
	prime.MessageModule,
	prime.MessagesModule,
	prime.OrderListModule,
	prime.OrganizationChartModule,
	prime.PaginatorModule,
	prime.PanelMenuModule,
	prime.PanelModule,
	prime.PasswordModule,
	prime.PickListModule,
	prime.ProgressBarModule,
	prime.ProgressSpinnerModule,
	prime.RadioButtonModule,
	prime.RatingModule,
	prime.ScheduleModule,
	prime.ScrollPanelModule,
	prime.SelectButtonModule,
	// prime.SharedModule
	prime.SidebarModule,
	prime.SlideMenuModule,
	prime.SliderModule,
	prime.SpinnerModule,
	prime.SplitButtonModule,
	prime.StepsModule,
	prime.TabMenuModule,

	prime.TabViewModule,
	prime.TerminalModule,
	prime.TieredMenuModule,
	prime.ToggleButtonModule,
	prime.ToolbarModule,
	prime.TooltipModule,
	prime.TreeModule,
	prime.TreeTableModule,
	prime.TriStateCheckboxModule,
	prime.AutoCompleteModule,
	prime.PanelModule
];
